[project]
org-name= "mosip"
version= "1.1.5.1"


[dependencies]
[platform]
target = "java8"
    [[platform.libraries]]
        module = "main"
        path = "./lib/postgresql-42.2.16.jar"
        groupId = "org.postgresql"
        artafactId = "postgresql"
        version = "42.2.16"
