[package]
org = "mosip"
name = "consolidatorService"
version = "1.2.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
modules = ["inittopic"]
groupId = "io.mosip"
artifactId = "kafka-admin-client"
version = "1.0.0"