[package]
org = "mosip"
name = "consolidatorService"
version = "1.2.0-patch1beta.2"


[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
modules = ["inittopic"]
groupId = "io.mosip"
artifactId = "kafka-admin-client"
version = "1.2.0.1-SNAPSHOT"
path = "kafka-admin-client/target/kafka-admin-client-1.2.0.1-SNAPSHOT.jar"
